import typing
from collections.abc import Iterator

import grpc
import pytest
from modern_di import Container

from modern_di_grpc import DIInterceptor, FromDI, fetch_di_container, inject
from tests.conftest import run_sync_server
from tests.dependencies import (
    AppResource,
    ContextReader,
    Dependencies,
    RequestResource,
    app_teardowns,
    request_teardowns,
)
from tests.protos import greeter_pb2, greeter_pb2_grpc


# greeter_pb2 is generated by protoc; ty (like most static checkers) can't see its dynamically
# built message attributes, so alias them once here instead of an ignore comment on every use below.
HelloRequest = greeter_pb2.HelloRequest  # ty: ignore[unresolved-attribute]
HelloReply = greeter_pb2.HelloReply  # ty: ignore[unresolved-attribute]


class Servicer(greeter_pb2_grpc.GreeterServicer):
    @inject
    def SayHello(  # noqa: N802
        self,
        request: HelloRequest,
        _context: grpc.ServicerContext,
        app_res: typing.Annotated[AppResource, FromDI(AppResource)],
        req_res: typing.Annotated[RequestResource, FromDI(Dependencies.request_factory)],
        ctx_reader: typing.Annotated[ContextReader, FromDI(Dependencies.context_reader)],
    ) -> HelloReply:
        assert fetch_di_container() is not None
        ok = isinstance(app_res, AppResource) and isinstance(req_res, RequestResource)
        # ctx_reader.peer proves grpc_context_provider injected the live ServicerContext into a factory
        return HelloReply(message=f"{request.name}:{ok}:{ctx_reader.peer}")

    @inject
    def SayHelloServerStream(  # noqa: N802
        self,
        request: HelloRequest,
        _context: grpc.ServicerContext,
        req_res: typing.Annotated[RequestResource, FromDI(Dependencies.request_factory)],
    ) -> Iterator[HelloReply]:
        for i in range(2):
            yield HelloReply(message=f"{request.name}:{i}:{isinstance(req_res, RequestResource)}")

    @inject
    def SayHelloClientStream(  # noqa: N802
        self,
        request_iterator: Iterator[HelloRequest],
        _context: grpc.ServicerContext,
        req_res: typing.Annotated[RequestResource, FromDI(Dependencies.request_factory)],
    ) -> HelloReply:
        names = ",".join(r.name for r in request_iterator)
        return HelloReply(message=f"{names}:{isinstance(req_res, RequestResource)}")

    @inject
    def SayHelloBidi(  # noqa: N802
        self,
        request_iterator: Iterator[HelloRequest],
        _context: grpc.ServicerContext,
        req_res: typing.Annotated[RequestResource, FromDI(Dependencies.request_factory)],
    ) -> Iterator[HelloReply]:
        for r in request_iterator:
            yield HelloReply(message=f"{r.name}:{isinstance(req_res, RequestResource)}")


@pytest.fixture
def sync_stub() -> Iterator[greeter_pb2_grpc.GreeterStub]:
    app_teardowns.clear()
    request_teardowns.clear()
    container = Container(groups=[Dependencies], validate=True)
    server, port = run_sync_server(Servicer(), DIInterceptor(container))
    with grpc.insecure_channel(f"127.0.0.1:{port}") as channel:
        yield greeter_pb2_grpc.GreeterStub(channel)
    server.stop(0)


def test_unary_unary(sync_stub: greeter_pb2_grpc.GreeterStub) -> None:
    resp = sync_stub.SayHello(HelloRequest(name="a"))
    name, ok, peer = resp.message.split(":", 2)
    assert (name, ok) == ("a", "True")
    assert peer.startswith(("ipv4:", "ipv6:"))  # grpc_context_provider injected the live ServicerContext
    assert request_teardowns == ["request-closed"]  # child closed after the RPC


def test_unary_stream(sync_stub: greeter_pb2_grpc.GreeterStub) -> None:
    msgs = [m.message for m in sync_stub.SayHelloServerStream(HelloRequest(name="b"))]
    assert msgs == ["b:0:True", "b:1:True"]
    assert request_teardowns == ["request-closed"]  # child survived streaming, closed after


def test_stream_unary(sync_stub: greeter_pb2_grpc.GreeterStub) -> None:
    it = iter([HelloRequest(name="c"), HelloRequest(name="d")])
    assert sync_stub.SayHelloClientStream(it).message == "c,d:True"
    assert request_teardowns == ["request-closed"]


def test_stream_stream(sync_stub: greeter_pb2_grpc.GreeterStub) -> None:
    it = iter([HelloRequest(name="e"), HelloRequest(name="f")])
    msgs = [m.message for m in sync_stub.SayHelloBidi(it)]
    assert msgs == ["e:True", "f:True"]
    assert request_teardowns == ["request-closed"]


async def test_app_finalizer_runs_on_root_close() -> None:
    app_teardowns.clear()
    container = Container(groups=[Dependencies], validate=True)
    server, port = run_sync_server(Servicer(), DIInterceptor(container))
    with grpc.insecure_channel(f"127.0.0.1:{port}") as channel:
        greeter_pb2_grpc.GreeterStub(channel).SayHello(HelloRequest(name="x"))  # resolves app_factory
    server.stop(0)
    await container.close_async()  # user-owned root lifecycle; AppResource's finalizer is async (see dependencies.py)
    assert app_teardowns == ["app-closed"]
