import typing
import unittest.mock
from collections.abc import AsyncIterator

import grpc
import grpc.aio
import pytest
from modern_di import Container

from modern_di_grpc import DIAioInterceptor, FromDI, fetch_di_container, grpc_context_provider, inject
from modern_di_grpc.main import _request_container, _wrap_unary_aio
from tests.dependencies import BoomDependencies, Dependencies, RequestResource, app_teardowns, request_teardowns
from tests.protos import greeter_pb2, greeter_pb2_grpc


# greeter_pb2 is generated by protoc; ty (like most static checkers) can't see its dynamically
# built message attributes, so alias them once here instead of an ignore comment on every use below.
HelloRequest = greeter_pb2.HelloRequest  # ty: ignore[unresolved-attribute]
HelloReply = greeter_pb2.HelloReply  # ty: ignore[unresolved-attribute]


class AioServicer(greeter_pb2_grpc.GreeterServicer):
    @inject
    async def SayHello(  # noqa: N802
        self,
        request: HelloRequest,
        _context: grpc.aio.ServicerContext,
        req_res: typing.Annotated[RequestResource, FromDI(Dependencies.request_factory)],
    ) -> HelloReply:
        return HelloReply(message=f"{request.name}:{isinstance(req_res, RequestResource)}")

    @inject
    async def SayHelloServerStream(  # noqa: N802
        self,
        request: HelloRequest,
        _context: grpc.aio.ServicerContext,
        req_res: typing.Annotated[RequestResource, FromDI(Dependencies.request_factory)],
    ) -> AsyncIterator[HelloReply]:
        for i in range(2):
            yield HelloReply(message=f"{request.name}:{i}:{isinstance(req_res, RequestResource)}")

    @inject
    async def SayHelloClientStream(  # noqa: N802
        self,
        request_iterator: AsyncIterator[HelloRequest],
        _context: grpc.aio.ServicerContext,
        req_res: typing.Annotated[RequestResource, FromDI(Dependencies.request_factory)],
    ) -> HelloReply:
        names = ",".join([r.name async for r in request_iterator])
        return HelloReply(message=f"{names}:{isinstance(req_res, RequestResource)}")

    @inject
    async def SayHelloBidi(  # noqa: N802
        self,
        request_iterator: AsyncIterator[HelloRequest],
        _context: grpc.aio.ServicerContext,
        req_res: typing.Annotated[RequestResource, FromDI(Dependencies.request_factory)],
    ) -> AsyncIterator[HelloReply]:
        async for r in request_iterator:
            yield HelloReply(message=f"{r.name}:{isinstance(req_res, RequestResource)}")


async def _make_server() -> tuple[grpc.aio.Server, int, Container]:
    container = Container(groups=[Dependencies], validate=True)
    server = grpc.aio.server(interceptors=[DIAioInterceptor(container)])
    greeter_pb2_grpc.add_GreeterServicer_to_server(AioServicer(), server)
    port = server.add_insecure_port("127.0.0.1:0")
    await server.start()
    return server, port, container


async def test_aio_unary_unary() -> None:
    request_teardowns.clear()
    server, port, _ = await _make_server()
    async with grpc.aio.insecure_channel(f"127.0.0.1:{port}") as channel:
        stub = greeter_pb2_grpc.GreeterStub(channel)
        resp = await stub.SayHello(HelloRequest(name="a"))
    assert resp.message == "a:True"
    assert request_teardowns == ["request-closed"]
    await server.stop(0)


async def test_aio_unary_stream() -> None:
    request_teardowns.clear()
    server, port, _ = await _make_server()
    async with grpc.aio.insecure_channel(f"127.0.0.1:{port}") as channel:
        stub = greeter_pb2_grpc.GreeterStub(channel)
        msgs = [m.message async for m in stub.SayHelloServerStream(HelloRequest(name="b"))]
    assert msgs == ["b:0:True", "b:1:True"]
    assert request_teardowns == ["request-closed"]
    await server.stop(0)


async def test_aio_stream_unary() -> None:
    request_teardowns.clear()
    server, port, _ = await _make_server()

    async def gen() -> AsyncIterator[HelloRequest]:
        yield HelloRequest(name="c")
        yield HelloRequest(name="d")

    async with grpc.aio.insecure_channel(f"127.0.0.1:{port}") as channel:
        stub = greeter_pb2_grpc.GreeterStub(channel)
        resp = await stub.SayHelloClientStream(gen())
    assert resp.message == "c,d:True"
    assert request_teardowns == ["request-closed"]
    await server.stop(0)


async def test_aio_stream_stream() -> None:
    request_teardowns.clear()
    server, port, _ = await _make_server()

    async def gen() -> AsyncIterator[HelloRequest]:
        yield HelloRequest(name="e")
        yield HelloRequest(name="f")

    async with grpc.aio.insecure_channel(f"127.0.0.1:{port}") as channel:
        stub = greeter_pb2_grpc.GreeterStub(channel)
        msgs = [m.message async for m in stub.SayHelloBidi(gen())]
    assert msgs == ["e:True", "f:True"]
    assert request_teardowns == ["request-closed"]
    await server.stop(0)


async def test_aio_unknown_method_returns_unimplemented() -> None:
    # No servicer is registered for this method, so continuation(...) returns None inside
    # DIAioInterceptor.intercept_service; gRPC then answers UNIMPLEMENTED on its own.
    server, port, _ = await _make_server()
    async with grpc.aio.insecure_channel(f"127.0.0.1:{port}") as channel:
        with pytest.raises(grpc.aio.AioRpcError) as excinfo:
            await channel.unary_unary("/greeter.Greeter/DoesNotExist")(b"")
        assert excinfo.value.code() == grpc.StatusCode.UNIMPLEMENTED
    await server.stop(0)


async def test_aio_app_finalizer_runs_on_root_close() -> None:
    app_teardowns.clear()
    server, port, container = await _make_server()
    async with grpc.aio.insecure_channel(f"127.0.0.1:{port}") as channel:
        stub = greeter_pb2_grpc.GreeterStub(channel)
        await stub.SayHello(HelloRequest(name="x"))
    await server.stop(0)
    # coveragepy #2124: on Python 3.11 the tracer can lose 1-2 lines right after awaiting
    # a coroutine that cancels tasks internally, which server.stop does to its own
    # background tasks. Excluded (not skipped) so the flake can't fail --cov-fail-under.
    await container.close_async()  # pragma: no cover
    assert app_teardowns == ["app-closed"]  # pragma: no cover


async def test_wrap_unary_aio_resets_context_var_when_close_raises() -> None:
    # Async twin of the sync wrapper-builder test: proves the reset still runs when
    # `await child.close_async()` raises (a REQUEST finalizer error).
    root = Container(groups=[BoomDependencies], validate=True)
    root.add_providers(grpc_context_provider)

    async def behavior(_request: object, _context: grpc.aio.ServicerContext) -> str:
        fetch_di_container().resolve_provider(BoomDependencies.boom_factory)
        return "ok"

    wrapped = _wrap_unary_aio(behavior, root)
    context = typing.cast(grpc.aio.ServicerContext, unittest.mock.MagicMock(spec=grpc.ServicerContext))

    with pytest.raises(RuntimeError, match="boom"):
        await wrapped(object(), context)

    with pytest.raises(LookupError):
        _request_container.get()

    await root.close_async()
